### ISSUE TITLE
Sometime in the past year this app stopped doing anything

### ISSUE THREAD

**Issue by dwlloyd810** [shybyte/tos-checker#21]
I was considering uninstalling this app because it hasn't been doing anything recently. I tested it on a number of EULAs and got no response. I decided to check if  others had  reported that the app quit working in the hope there might be a new version I could install or a workaround.

**Comment by shybyte** [comment]
There is currently work going on to base the chrome-extension and firefox-addon on a common code base. See here https://github.com/tosdr/browser-extensions. The new extension is currently being released.
I will soon deprecate this repo.
